alkemyTech/OT196-Server

- app.js
- migrations/20220519174858-create-testimony.js
- models/testimony.js
- routes/testimonials.js
- seeders/20220519175346-create-demo-testimony.js
https://alkemy-labs.atlassian.net/browse/OT196-17
- Testimony model
- Testimony migration
- Testimony seeder
- Testimonials/organization routes file
- Testimonials/organization endpoint
> New module Testimony and endpoint to get that data

- controllers/userValidator.js
- routes/users.js
Dejo a continuación evidencia del endpoint de autenticación funcionando.
> POST user authenticate and password encrypted

- app.js
- controllers/authController.js
- middlewares/validators/formsValidator.js
- package.json
- routes/auth.js
https://alkemy-labs.atlassian.net/browse/OT196-25
**Features**
- POST endpoint
- Email & password validation on request (formsValidator scheme on post request)
- Validate if email is registered (authController)
- Compare db hashed password with password on request using bcrypt (authController)
**Evidence**
Non-existent account
Bad login credentials
Correct request
> [OT196-25] Endpoint de autenticación

- middlewares/validators/userValidator.js
- middlewares/validators/userValidators.js
https://alkemy-labs.atlassian.net/browse/OT196-52
**Features**
- Created middleware that allows to check if user have admin role when make a request
- Admin roles must be on the array (default: [1])
**Evidence**
_Note: Evidence was made with a test endpoint._
Request without token
Request with malformed token
Request with user without admin role
Request success
> [OT196-52] Middleware for verificate if user is admin

- migrations/20220526194839-create-entry.js
- models/entry.js
- seeders/20220526192849-create-demo-entry.js
https://alkemy-labs.atlassian.net/browse/OT196-40
**Features**
- Created new model Entry (tablename Entries)
- Created migration and seeder for Entry model
- _Attribute type_ have validation, only accept: _news_, _event_ or _other_
- _Attribute content_ have max lenght of 2500 chars.
**Evidence**
> [OT196-40] Create model and migration for news

- routes/users.js
- Route GET /users
- Accessing from a role other than administrator:
- Accessing from an administrator role:
> Endpoint for User list

- models/index.js
- routes/news.js
Fix to allow work on: https://alkemy-labs.atlassian.net/browse/OT196-58
Fix of: https://github.com/alkemyTech/OT196-Server/pull/12
**Features**
- Added ID attribute & status code to response
- Mistyping from a previous merge
**Evidence**
-
> [FIX-OT196-45] Fix news list endpoint

- migrations/20220602143013-create-contact.js
- models/contact.js
- seeders/20220602143522-demo-contact.js
https://alkemy-labs.atlassian.net/browse/OT196-71
- Contact model
- Contact migration
- Contact seeder
> [OT196-71] Created migration and contact model

- migrations/20220605202046-create-organizations.js
- migrations/20220605202050-update-testimony.js
- models/organization.js
- models/testimony.js
- seeders/20220519175346-create-demo-testimony.js
- seeders/20220605202046-create-demo-organizations.js
https://alkemy-labs.atlassian.net/browse/OT196-81
> Al hacer esta tarea surgió que la tarea del PR #1 ya había creado el modelo de testimonios debido a que en la tarea de Jira hablaba de testimonios. 
> ![image](https://user-images.githubusercontent.com/66728462/172071417-060fb25d-e222-47cf-aede-9bc46e3e06bc.png)
>Asumo que fue un error de tipeo en esa tarea ya que es una tarea relacionada a organizaciones y un endpoint de organizaciones por ello renombro lo que previamente fue creado como modelo y migración de testimonios a organizaciones, y procedo a crear de cero el modelo y migración de testimonios. De esta forma quedan creados el modelo/migracion de testimonios y organizaciones que también será necesario para otras tareas.
**Features**
-
- Renamed old _Testimony_ migrations & model …
> [OT196-81] Create model & migration for Testimonials

- app.js
- controllers/activitiesController.js
- routes/activities.js
https://alkemy-labs.atlassian.net/browse/OT196-68
This is just an endpoint that I need to accomplish the task on the front-end.
- New GET route: **/activities/:id**
- New controller (activitiesController) to handle the activities routes.
> [OT196-68] Endpoint to GET Activities' Details

- app.js
- controllers/validateTestimony.js
- routes/testimonials.js
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT196/boards/276?modal=detail&selectedIssue=OT196-84
Endpoint for testimonials and validator data
> [OT196-84]Endpoint Post for Testimonials

- controllers/contactsController.js
- utils/emailSender.js
https://alkemy-labs.atlassian.net/browse/OT196-75
- Used sendEmail on the Contact's controller.
- Thanks message in the email.
Request and response:
Email received from the app:
Server status:
> [OT196-75] Send contact email

- controllers/newsController.js
- routes/news.js
> Despues del mergeo a main de los PR #15 y #14 quedaron unos errores al resolver los conflictos de las ramas respecto a main.
> [Fix] Fixing errors on news route after merge

- app.js
- routes/testimonials.js
https://alkemy-labs.atlassian.net/browse/OT196-86
-Fix endpoint Get for testimonials and route in app.js
-Create endpoint Delete
Cree el endpoint Delete para probar la tarea de screen testimonials. Asi que decidí enviarlo para adelantar un poco.
> [OT196-86]fix Get testimonials and create endpoint Delete

- app.js
- controllers/categoriesController.js
- migrations/20220609144631-update-category.js
- models/category.js
- routes/categories.js
- seeders/20220601134624-demo-category.js
https://alkemy-labs.atlassian.net/browse/OT196-98
- New migration to update the table: _Categories_ instead of _categories_ to maintain the format we have been doing
- Updated model and seeder
- Categories router in app
- New endpoint: PUT **/categories/:id**
- New controller to update category
- If the user does not have an admin role:
- If the user wants to update an unexistent category:
- If the user wants to update with both values (name and desccription):
- If the user wants to update without one of the values:
- Changes reflected in the DB:
> [OT-196-98] Endpoint Update Category

- migrations/20220603124104-create-activity.js
- migrations/20220609145138-Update-activity.js
- models/activity.js
- seeders/20220601171146-create-demo-activity.js
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT196/boards/276?modal=detail&selectedIssue=OT196-69 
-Update content of table Activities
-Fill seeder with ONG data
> [OT196-69]Create seeder with data of ONG

- controllers/usersController.js
- routes/users.js
https://alkemy-labs.atlassian.net/browse/OT196-57
https://alkemy-labs.atlassian.net/browse/OT196-51
This endpoint is needed for the Edit User's Form in the client. Also, i linked both tasks (OT196-57 and OT196-51) because I'm creating a PR for both tasks at the same time (one was from a previous coder who leaved)
- New controller to update users.
- New route: **PUT /users/:id**
- Moved existing functions in /routes/users to /controllers/usersController.
- If the user is admin:
- If the user is not admin:
Change showed in DB:
- Before:
- After:
> [OT196-51] Endpoint Update user

- routes/news.js
OT196-63_DeleteNewsEndpoint](https://alkemy-labs.atlassian.net/browse/OT196-63
**Features**
-Add endpoint delete.
-Add validator.
**Evidence**
Before delete
Entry deleted
> Ot196 63 delete news endpoint

- app.js
- middlewares/validators/formsValidator.js
- routes/activities.js
- routes/testimonials.js
https://alkemy-labs.atlassian.net/browse/OT196-85
Creando ruta para actualizar testimonios
> route for update testimonials

- migrations/20220610213336-create-members.js
- models/members.js
https://alkemy-labs.atlassian.net/browse/OT196-88
Agregando migración y modelo de miembros. 
Visualizando tabla desde workbench:
> adding migration and model

- app.js
- controllers/membersController.js
- middlewares/validators/membersValidator.js
- routes/members.js
https://alkemy-labs.atlassian.net/jira/software/c/projects/OT196/boards/276?modal=detail&selectedIssue=OT196-90
-Add route /members
-Add member validator and member controller
-Note: Añadí el parámetro image de forma opcional, para que la petición pueda ser mas completa. Ya que image se encuentra en el modelo de members.
> [OT196-90] Create Post members

- controllers/membersController.js
- controllers/testimonialsController.js
- routes/testimonials.js
> Fix GET testimonials/members

- controllers/categoriesController.js
https://alkemy-labs.atlassian.net/browse/OT196-111
This task needs an endpoint to return one more value.
- GET /categories: List returned now has one more attribute on each category: description.
> [OT196-111] Categories ABM Revision

- controllers/authController.js
- controllers/usersController.js
- routes/auth.js
- routes/users.js
- The endpoint /users/auth/me no longer exists
- New enpoint in /auth routes: GET /me
- Endpoint fixed so it can return data based on the logged user (via its JWT token)
- Trying endpoint with token from a user existing in the DB (id is 1):
> [OT196-FIX] Endpoint /auth/me

- package.json
- tests/members.spec.js
Añandiendo Testing para endpoint de members usando la libreria Jest. 
Se añadieron varios test para comprobar el correcto funcionamiento de los endpoints
> adding testing for members

- controllers/newsController.js
- middlewares/validators/formsValidator.js
- package.json
- routes/news.js
- test/news.test.js
https://alkemy-labs.atlassian.net/browse/OT196-116
**Features**
- Fix response on non-existent id (PUT & GET)
- Add admin validation on PUT & DELETE
- Tests on news endpoint
- Test required fields on POST & PUT
- Test existent ID on GET, PUT & DELETE
- Test admin token on POST, PUT & DELETE
**Evidence**
-
> [OT196-116] Test news endpoint
